# Project Title 
# Student Course Enrollment management system
/* Business Problem : In a training Institute the data is stored in Excel.
As the number of students increasing manually analyzing/trcaking the data is difficult. */
/*Objective :
we need a system which tracks students details,courses,enrollments,instructors which is easy to track the details. */

Create database sqlproject;
use sqlproject;
create table students(StudentID int primary key,
studentName varchar(20),
Gender varchar(10),
Age int,
City varchar(20),
Email varchar(30),
Phone varchar(20),
JoiningDate Date);  
select * from students;

Create table Instructors(InstructorID int primary key,
InstructorName varchar(20),
Department Varchar(20),
Experience int);
select * from Instructors;

create table Courses(CourseID int primary key,
CourseName varchar(20),
DurationMonth int,
Fee Decimal(10,2),
InstructorID int,
foreign key (InstructorID)
references Instructors(InstructorID));
select * from courses;

create table Enrollments(EnrollmentID int primary key,
StudentID int,
CourseID int,
EnrollmentDate Date,
CompletionStatus varchar(20),
Marks int,
foreign key (StudentID)
references Students(StudentID),
foreign key (CourseID)
references Courses(CourseID));

select * from Enrollments;

# Business Analyzing Questions
# 1. Total number of students
select count(*) as Total_Students from students;
#Insight
# There are Total 100 Students in the institute


# 2.Total number of Couses
select count(*) as Total_courses from courses;
# Insights
# There are Total 5 courses there in the institute

# 3. Total number of instructors
select count(*) as Total_Instructors from Instructors;
# Insigts
# There are total 5 Instructors in the institute

#4.Courses with fee greater than 5000
select * from courses where fee>5000;
#For python,Power bI and Data Analytics courses fee is more than 5000

# 5. Studets Enrolled in each course
select 
c.CourseName,
count(e.StudentID) as total_students
from Courses c
join Enrollments e
on c.CourseID=e.CourseID
group by c.CourseName;
# most students are enrolled in data analytics

#6. List students with there courses
SELECT s.StudentName,
       c.CourseName
FROM Students s
JOIN Enrollments e
ON s.StudentID = e.StudentID
JOIN Courses c
ON e.CourseID = c.CourseID;

# 7. Students who complete there courses
select s.studentname,
c.coursename,
e.completionstatus
from students s
join enrollments e
on s.studentid = e.studentid
join courses c
on c.courseid = e.courseid
where completionstatus="COmpleted";

# 8. students who are still studying
select s.studentname,
c.coursename,
e.completionstatus
from students s
join enrollments e
on s.studentid = e.studentid
join courses c
on c.courseid = e.courseid
where completionstatus="Ongoing";

#9.city wise student count
select city,count(*) as total_students from students group by city;
# Using SQL Query , I have analyzed that most of the students are from Hyderabad

#10. Revenue generated by each course
select c.coursename,
count(e.studentId)* c.fee as revenue
from enrollments e 
join courses c
on e.courseid = c.courseid
group by c.coursename, c.fee;
# Highest revenue is generated from data analytics
# Least revenue is generated from excel.